default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: sitemap_dev

test:
  <<: *default
  database: sitemap_test

production:
  <<: *default
  database: sitemap_prod
